import { useState, useEffect, useRef } from 'react';
import { Terminal, ShieldAlert, Loader2, ArrowDownCircle, Search } from 'lucide-react';
import { JobLog } from '../types';

export default function LogsView() {
  const [logs, setLogs] = useState<JobLog[]>([]);
  const [levelFilter, setLevelFilter] = useState<string>('');
  const [searchText, setSearchText] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const terminalEndRef = useRef<HTMLDivElement | null>(null);

  const fetchLogs = async () => {
    try {
      const res = await fetch('/api/logs?pageSize=100');
      const data = await res.json();
      setLogs(data.data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
    const interval = setInterval(fetchLogs, 3000);
    return () => clearInterval(interval);
  }, []);

  // Filter logs locally for continuous fluid stream
  const filteredLogs = logs.filter((log) => {
    const matchesLevel = levelFilter ? log.level === levelFilter : true;
    const matchesText = searchText
      ? log.message.toLowerCase().includes(searchText.toLowerCase()) ||
        log.job_id.toString().includes(searchText) ||
        (log.job_type && log.job_type.toLowerCase().includes(searchText.toLowerCase()))
      : true;
    return matchesLevel && matchesText;
  });

  return (
    <div className="space-y-6 py-2">
      {/* Header Panel */}
      <div className="pb-2 border-b border-slate-200">
        <h2 className="text-xl font-display font-semibold text-slate-900">Job Execution Logs</h2>
        <p className="text-slate-500 text-xs mt-0.5">Stream and query decentralized server logs generated by background jobs in real-time.</p>
      </div>

      {/* Terminal Control bar */}
      <div className="bg-slate-900 border-b border-slate-800 rounded-t-md p-3 flex flex-col md:flex-row gap-3 justify-between items-center">
        {/* Terminal label */}
        <div className="flex items-center gap-2 text-indigo-400 font-mono text-xs">
          <Terminal className="w-4 h-4" />
          <span>CONSOLE: job_scheduler_stdout</span>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-2">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-2.5 top-2 w-3.5 h-3.5 text-slate-500" />
            <input
              type="text"
              placeholder="Filter console..."
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              className="pl-8 pr-3 py-1 bg-slate-950 border border-slate-800 text-slate-300 rounded font-mono text-[11px] outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20"
            />
          </div>

          {/* Level tabs */}
          <div className="bg-slate-950 border border-slate-800 rounded p-0.5 flex gap-1 font-mono text-[10px]">
            <button
              onClick={() => setLevelFilter('')}
              className={`px-2 py-0.5 rounded transition cursor-pointer ${
                levelFilter === '' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              ALL
            </button>
            <button
              onClick={() => setLevelFilter('info')}
              className={`px-2 py-0.5 rounded transition cursor-pointer ${
                levelFilter === 'info' ? 'bg-emerald-600/20 text-emerald-400 border border-emerald-500/10' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              INFO
            </button>
            <button
              onClick={() => setLevelFilter('warn')}
              className={`px-2 py-0.5 rounded transition cursor-pointer ${
                levelFilter === 'warn' ? 'bg-amber-600/20 text-amber-400 border border-amber-500/10' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              WARN
            </button>
            <button
              onClick={() => setLevelFilter('error')}
              className={`px-2 py-0.5 rounded transition cursor-pointer ${
                levelFilter === 'error' ? 'bg-rose-600/20 text-rose-400 border border-rose-500/10' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              ERROR
            </button>
          </div>
        </div>
      </div>

      {/* Terminal Display */}
      <div className="bg-slate-950 border border-slate-900 rounded-b-md p-4 min-h-96 max-h-[500px] overflow-y-auto space-y-1 font-mono text-[11px] text-slate-300 leading-normal scroll-smooth">
        {loading && logs.length === 0 ? (
          <div className="flex justify-center items-center h-48">
            <Loader2 className="w-6 h-6 text-indigo-500 animate-spin" />
          </div>
        ) : filteredLogs.length === 0 ? (
          <p className="text-slate-500 italic text-center py-12">No matching telemetry logs found in current buffer.</p>
        ) : (
          filteredLogs.map((log) => {
            let levelColor = 'text-slate-400';
            if (log.level === 'error') levelColor = 'text-rose-400 font-bold';
            else if (log.level === 'warn') levelColor = 'text-amber-400 font-bold';
            else if (log.level === 'info') levelColor = 'text-emerald-400';

            return (
              <div key={log.id} className="hover:bg-slate-900/40 p-1 rounded flex gap-4 transition items-start">
                <span className="text-slate-600 select-none flex-shrink-0 w-20">
                  {new Date(log.created_at).toLocaleTimeString([], { hour12: false, fractionalSecondDigits: 3 } as any)}
                </span>
                <span className={`w-12 select-none uppercase font-bold text-center flex-shrink-0 ${levelColor}`}>
                  {log.level}
                </span>
                <span className="text-indigo-400 select-none flex-shrink-0 font-bold w-16">
                  [JOB #{log.job_id}]
                </span>
                <span className="text-slate-200 whitespace-pre-wrap font-sans">
                  {log.message}
                </span>
              </div>
            );
          })
        )}
        <div ref={terminalEndRef} />
      </div>
    </div>
  );
}
